language: rust
sudo: false
dist: trusty

cache:
  cargo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: 1.42.0
    - rust: nightly

before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      rustup component add rustfmt
      rustup component add clippy
    fi

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      cargo fmt -- --check
      cargo clippy --all-targets --features bytes-buf -- -D warnings
    fi
  - cargo test --features bytes-buf --all -- --nocapture
  - cargo test --features bytes-buf-tokio3 --all -- --nocapture
