[package]
name = "buf-min"
version = "0.0.2"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Minimal buffer traits"
keywords = ["buffers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/botika/buf-min"
documentation = "https://docs.rs/buf-min"
edition = "2018"

[features]
bytes-buf = ["bytes"]

[dependencies]
bytes = { version = "0.5", optional = true }
