[package]
name = "buf-min"
version = "0.1.1"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Minimal buffer traits"
keywords = ["buffers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/botika/buf-min"
documentation = "https://docs.rs/buf-min"
edition = "2018"

[features]
bytes-buf = ["bytes"]

[dependencies]
bytes = { git = "https://github.com/botika/bytes", rev = "03f963b", optional = true }

[package.metadata.docs.rs]
all-features = true
