[package]
name = "buf-min"
version = "0.0.1"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
edition = "2018"

[features]
bytes-buf = ["bytes"]

[dependencies]
bytes = { version = "0.5", optional = true }
